# Generated by Django 4.0.3 on 2022-07-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='user',
            name='firebase_user_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
