services:
  api:
    build: .
    image: palmarosa/tight-lines:django_api_1
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - POSTGRES_DB=railway
      - POSTGRES_USER=Postgres
      - POSTGRES_PASSWORD=z7fJmknUIMS54vuC3Ecg
  database:
    image: postgres:13
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/pgsql/data
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=railway
      - POSTGRES_USER=Postgres
      - POSTGRES_PASSWORD=z7fJmknUIMS54vuC3Ecg

volumes:
  db-data:
