# Generated by Django 4.0.3 on 2022-07-16 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('river', models.CharField(blank=True, choices=[('Tongariro', 'Tongariro'), ('Tauranga Taupo', 'Tauranga Taupo'), ('Lake O', 'Lake O')], default=None, max_length=14, null=True)),
                ('river_pool', models.CharField(max_length=20, verbose_name='what pool?')),
                ('river_geotag', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='geotag coordinates option here')),
                ('river_level', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('air_pressure', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fish_species', models.CharField(blank=True, choices=[('Rainbow', 'Rainbow'), ('Brown', 'Brown')], default=None, max_length=7, null=True)),
                ('fish_weight', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fish_length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fish_condition', models.CharField(blank=True, choices=[('Sick/Spawning', 'Sick or spawning'), ('Average', 'Average'), ('Healthy', 'Healthy'), ('Sashimi', 'Sashimi')], default=None, max_length=13, null=True)),
                ('kept_or_released', models.BooleanField(blank=True, default=None, null=True, verbose_name='Kept for dinner?')),
                ('fly_used', models.CharField(max_length=25)),
                ('any_notes', models.CharField(max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
