# Generated by Django 4.1.7 on 2023-02-22 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FishingLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('region', models.CharField(blank=True, choices=[('Northland', 'Northland'), ('Auckland/Waikato', 'Auckland/Waikato'), ('Eastern/Rotorua', 'Eastern/Rotorua'), ("Hawke's Bay", "Hawke's Bay"), ('Taupo/Turangi', 'Taupo/Turangi'), ('Taranaki', 'Taranaki'), ('Wellington', 'Wellington'), ('Nelson/Marlborough', 'Nelson/Marlborough'), ('North Canterbury', 'North Canterbury'), ('West Coast', 'West Coast'), ('Central South Island', 'Central South Island'), ('Otago', 'Otago'), ('Southland', 'Southland')], default='None', max_length=20, null=True)),
                ('river', models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='river')),
                ('river_pool', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='what pool?')),
                ('lat', models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lat')),
                ('lon', models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lon')),
                ('image', models.ImageField(blank=True, default=None, max_length=254, null=True, upload_to='photos/%Y/%m/%d/')),
                ('river_level', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('air_pressure', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fish_species', models.CharField(blank=True, choices=[('Rainbow', 'Rainbow'), ('Brown', 'Brown')], default=None, max_length=7, null=True)),
                ('fish_weight', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fish_length', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('fish_condition', models.CharField(blank=True, choices=[('Spent', 'Spent'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default=None, max_length=19, null=True)),
                ('kept_or_released', models.CharField(blank=True, choices=[('Kept', 'Kept'), ('Released', 'Released')], default=None, max_length=8, null=True, verbose_name='Kept for dinner?')),
                ('fly_used', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('any_notes', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('number_of_fish', models.IntegerField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(default='noFirebaseUserID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
