# Generated by Django 4.1.1 on 2022-11-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishinglogentry',
            name='river_geotag',
        ),
        migrations.AddField(
            model_name='fishinglogentry',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='fishinglogentry',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lon'),
        ),
        migrations.AddField(
            model_name='fishinglogentry',
            name='number_of_fish',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='fishinglogentry',
            name='any_notes',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishinglogentry',
            name='fish_condition',
            field=models.CharField(blank=True, choices=[('Spent', 'Spent'), ('Average', 'Average'), ('Good', 'Good'), ('Excellent', 'Excellent')], default=None, max_length=19, null=True),
        ),
        migrations.AlterField(
            model_name='fishinglogentry',
            name='fly_used',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='fishinglogentry',
            name='river',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='river'),
        ),
        migrations.AlterField(
            model_name='fishinglogentry',
            name='river_pool',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='what pool?'),
        ),
    ]
