# Generated by Django 4.0.3 on 2022-08-21 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinglogentry',
            name='fish_condition',
            field=models.CharField(blank=True, choices=[('Sick/Spawning', 'Sick/Spawning'), ('Average', 'Average'), ('Healthy', 'Healthy'), ('Sashimi', 'Sashimi')], default=None, max_length=13, null=True),
        ),
    ]
