# Generated by Django 4.0.3 on 2022-09-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0002_alter_fishinglogentry_fish_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishinglogentry',
            name='river_geotag',
        ),
        migrations.AddField(
            model_name='fishinglogentry',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='fishinglogentry',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lon'),
        ),
    ]
