# Generated by Django 4.0.3 on 2022-09-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0002_alter_fishinglogentry_fish_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishinglogentry',
            name='river_geotag',
        ),
    ]
