# Generated by Django 4.0.3 on 2022-09-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0003_remove_fishinglogentry_river_geotag'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishinglogentry',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lat'),
        ),
        migrations.AddField(
            model_name='fishinglogentry',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=16, default=None, max_digits=22, null=True, verbose_name='lon'),
        ),
    ]
