# Generated by Django 4.0.3 on 2022-09-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0004_fishinglogentry_lat_fishinglogentry_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinglogentry',
            name='any_notes',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fishinglogentry',
            name='fly_used',
            field=models.CharField(blank=True, default=None, max_length=25, null=True),
        ),
    ]
