# Generated by Django 4.0.3 on 2022-09-07 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trout', '0006_alter_fishinglogentry_fish_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishinglogentry',
            name='river_pool',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='what pool?'),
        ),
    ]
